version: "3"

services:
  db: 
    container_name: "mongo"
    image: mongo
    
    ports:
      - "27017:27017"

  app: 
    container_name: "api"
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - db

  